### PR TITLE
add Nigerian Laws 1992 National Drug Law Enforcement Agency Decree 1992

### PR DESCRIPTION
**Pull request by chikiwawa**
Adding to the 1992 Nigerian Laws.
Please feel free to edit to comment if something is incorrect

### CODE REVIEW

**Comment by mykeels** [comment]
The file's extension is now `*.md.mdown` when it should be just `*.md` 😀

**Comment by chikiwawa** [comment]
DId you fix the extension? Just curious.
I noticed that even when I had renamedt he file for some reason my extension ended up being .md.mdown
But when I kept going back to the file folder the extension showed up as .md
Is there a reason for this? Just making sure so any future contributions I can diagnose the issue.

**Comment by mykeels** [comment]
Yes, I've renamed it. If you're using Windows, your file extensions are probably hidden.

You can unhide them, and it's probably preferable to do so.

**Comment by chikiwawa** [comment]
Thanks for the heads up!
I go back and forth between Mac & Windows.
I will make sure that my extensions are unhidden so I don't run into the issue again when using Windows.

**Pull request merged**
