### PR TITLE
Add Marriage Act, 1990 and Oil Pipelines Act, 1990

### PR DESCRIPTION
**Pull request by krizten**
### The following files have been included in the repository under the 1990 directory. 
* Marriage Act, 1990.pdf             (7 pages)
* Oil Pipelines Act, 1990.pdf       (9 pages)

### CODE REVIEW

**Comment by mykeels** [comment]
Hi @krizten ... the files should be in markdown format. I could help with it if you send them as an attachment to my email

**Comment by mykeels** [comment]
Found them here as HTML

- http://www.nigeria-law.org/Marriage%20Act.htm
- http://www.nigeria-law.org/Oil%20Pipelines%20Act.htm

**Comment by krizten** [comment]
Okay, I will forward them to your email (mykehell123@gmail.com).

**Comment by mykeels** [comment]
Added

- https://github.com/mykeels/nigerian-laws/blob/master/1990/Marriage-Act-1990.md
- https://github.com/mykeels/nigerian-laws/blob/master/1990/Oil-Pipelines-Act-1990.md

Thanks, @krizten

**Pull request closed without merging**
